### ISSUE TITLE
Update Documentation to inlcude instructions on vars to config for users

### ISSUE THREAD

**Issue by gregorskii** [michaelrigart/ansible-role-capistrano-setup#1]
Hi there,

The documentation on this role does not define all of the values needed to create a user for the deployment.

Can you provide a full example of what variables to set on run?

**Comment by michaelrigart** [comment]
Hi,

what do you mean by not defining all of the values needed? I checked the documentation and all variables are present.

As an example:

```
capistrano_setup_users:
  - username: 'gregorskii'
    groups:
      - 'gregorskii'
    shell: '/bin/bash'
    name: 'gregorskii'
    uid: 2000
    home: '/srv/gregorskii'
    createhomedir: 'yes'
    password:
    update_password: 'on_create'
    upload_keyt: 'yes'
    pub_key: 'gregorskii.pub'
    project_directory: 'www'
  - username: 'michaelrigart'
    groups:
      - 'michaelrigart'
      - 'sudo'
    shell: '/bin/bash'
    name: 'Michaël Rigart'
    uid: 2001
    home: '/srv/michael'
    createhomedir: 'yes'
    password:
    update_password: 'on_create'
    upload_key: 'yes'
    pub_key: 'michael.pub'
    project_directory: 'www'
```
